/******************************************************************************
(C) Copyright 2020-2022 Real-Time Innovations, Inc.  All rights reserved.

The use of this software is governed by the terms specified in the 
RTI Labs License Agreement, available at https://www.rti.com/terms/RTILabs. 

By accessing, downloading, or otherwise using this software, you agree to 
be bound by those terms.
*****************************************************************************/

#ifndef ACTUATION_SVC_IDL
#define ACTUATION_SVC_IDL

#include "res/types/services/Drive_bus_t.idl"
#include "res/types/data/actuation/Actuation_t.idl"

module dds {
    /*************************************************************************
     * Service Interfaces - DDS-XML Interface String Constants, for use in code
     */
    module Actuation_svc {
        module Actuator {
            const string participant    = "Actuation_svc::Actuator";
            module reader {
                const string Steering   = "inputs::Steering_reader";
            };
            module writer {
                const string Steering   = "outputs::Steering_writer";
            };
        };
   };
};

#endif /* ACTUATION_SVC_IDL */
