/*****************************************************************************
  (c) 2020 Copyright, Real-Time Innovations, Inc. (RTI) All rights reserved.

   Licensed according to the terms in the LICENSE.md file located at the root 
   of this software repository:

                                LICENSE.md

*****************************************************************************/
#ifndef HMI_SVC_IDL
#define HMI_SVC_IDL

#include "res/types/services/Drive_bus_t.idl"
#include "res/types/data/planning/Alert_t.idl"

module dds {
    /*************************************************************************
     * Service Interfaces - DDS-XML Interface String Constants, for use in code
     */
    module HMI_svc {
        module HMI {
            const string participant    = "HMI_svc::HMI";
            module reader {
                const string Alert      = "outputs::Alert_reader";
            };
        };
   };
};

#endif /* HMI_SVC_IDL */
