/******************************************************************************
(C) Copyright 2020-2022 Real-Time Innovations, Inc.  All rights reserved.

The use of this software is governed by the terms specified in the 
RTI Labs License Agreement, available at https://www.rti.com/terms/RTILabs. 

By accessing, downloading, or otherwise using this software, you agree to 
be bound by those terms.
*****************************************************************************/

#ifndef HMI_SVC_IDL
#define HMI_SVC_IDL

#include "res/types/services/Drive_bus_t.idl"
#include "res/types/data/planning/Alert_t.idl"

module dds {
    /*************************************************************************
     * Service Interfaces - DDS-XML Interface String Constants, for use in code
     */
    module HMI_svc {
        module HMI {
            const string participant    = "HMI_svc::HMI";
            module reader {
                const string Alert      = "outputs::Alert_reader";
            };
        };
   };
};

#endif /* HMI_SVC_IDL */
