/******************************************************************************
(C) Copyright 2020-2022 Real-Time Innovations, Inc.  All rights reserved.

The use of this software is governed by the terms specified in the 
RTI Labs License Agreement, available at https://www.rti.com/terms/RTILabs. 

By accessing, downloading, or otherwise using this software, you agree to 
be bound by those terms.
*****************************************************************************/

#ifndef PERCEPTION_IDL
#define PERCEPTION_IDL

#include "res/types/services/Drive_bus_t.idl"
#include "res/types/data/sensing/Camera_t.idl"
#include "res/types/data/sensing/Lidar_t.idl"
#include "res/types/data/perception/Track_t.idl"
#include "res/types/data/perception/Lane_t.idl"

module dds {
    /*************************************************************************
     * Service Interfaces - DDS-XML Interface String Constants, for use in code
     */
    module Perception_svc {
        module Perceptor {
            const string participant    = "Perception_svc::Perceptor";
            module reader {
                const string Camera     = "inputs::Camera_reader";
                const string Lidar      = "inputs::Lidar_reader";
            };
            module writer {
                const string Track      = "outputs::Track_writer";
                const string Lane       = "outputs::Lane_writer";
            };
        };
   };
};

#endif /* PERCEPTION_IDL */
