/******************************************************************************
(C) Copyright 2020-2022 Real-Time Innovations, Inc.  All rights reserved.

The use of this software is governed by the terms specified in the 
RTI Labs License Agreement, available at https://www.rti.com/terms/RTILabs. 

By accessing, downloading, or otherwise using this software, you agree to 
be bound by those terms.
*****************************************************************************/

#ifndef PLANNING_IDL
#define PLANNING_IDL

#include "res/types/services/Drive_bus_t.idl"
#include "res/types/data/perception/Track_t.idl"
#include "res/types/data/perception/Lane_t.idl"
#include "res/types/data/planning/Alert_t.idl"
#include "res/types/data/actuation/Actuation_t.idl"

module dds {
    /*************************************************************************
     * Service Interfaces - DDS-XML Interface String Constants, for use in code
     */
    module Perception_svc {
        module Planner {
            const string participant    = "Planning_svc::Planner";
            module reader {
                const string Track      = "inputs::Track_reader";
                const string Lane       = "inputs::Track_reader";
                const string Steering   = "inputs::Steering_reader";
            };
            module writer {
                const string Steering   = "outputs::Steering_writer";
                const string Alert      = "outputs::Alert_writer";
            };
        };
   };
};

#endif /* PLANNING_IDL */
