/******************************************************************************
(C) Copyright 2020-2022 Real-Time Innovations, Inc.  All rights reserved.

The use of this software is governed by the terms specified in the 
RTI Labs License Agreement, available at https://www.rti.com/terms/RTILabs. 

By accessing, downloading, or otherwise using this software, you agree to 
be bound by those terms.
*****************************************************************************/

#ifndef SENSING_SVC_IDL
#define SENSING_SVC_IDL

#include "res/types/services/Drive_bus_t.idl"
#include "res/types/data/sensing/Camera_t.idl"
#include "res/types/data/sensing/Lidar_t.idl"

module dds {
    /*************************************************************************
     * Service Interfaces - DDS-XML Interface String Constants, for use in code
     */
    module Sensing_svc {
        module Camera {
            const string participant    = "Sensing_svc::Camera";
            module writer {
                const string Camera     = "outputs::Camera_writer";
            };
        };
        module Lidar {
            const string participant    = "Sensing_svc::Lidar";
            module writer {
                const string Lidar      = "outputs::Lidar_writer";
            };
        };
    };
};

#endif /* SENSING_SVC_IDL */
