/******************************************************************************
(C) Copyright 2020-2022 Real-Time Innovations, Inc.  All rights reserved.

The use of this software is governed by the terms specified in the 
RTI Labs License Agreement, available at https://www.rti.com/terms/RTILabs. 

By accessing, downloading, or otherwise using this software, you agree to 
be bound by those terms.
*****************************************************************************/

#ifndef SHAPES_IDL
#define SHAPES_IDL

module dds {
    /*************************************************************************
     * Databus - DDS-XML Interface String Constants, for use in code
     */
    module Shapes_bus {

        module registered_type {
            const string ShapeType      = "ShapeType";
        };

        module topic {
            const string Square         = "Square";
            const string Circle         = "Circle";
            const string Triangle       = "Triangle";
        }; 
    };

    /*************************************************************************
    * Service Interfaces - DDS-XML Interface Name Constants, for use in code
    */
    module Shapes_svc {
        module Pub {
            const string participant    = "Shapes_svc::Pub";
            module writer {
                const string Shape      = "outputs::Shape_writer";
            };
        };
        module Sub {
            const string participant    = "Shapes_svc::Sub";
            module reader {
                const string Shape      = "inputs::Shape_reader";
            };
        };
        module PubSub {
            const string participant    = "Shapes_svc::PubSub";
            module reader {
                const string Shape      = "inputs::Shape_reader";
            };
            module writer {
                const string Shape      = "outputs::Shape_writer";
            };
        };
    };
};
#endif /* SHAPES_IDL */
